### ISSUE TITLE
Error  dec.buf.Discard undefined

### ISSUE THREAD

**Issue by izac1** [pixelbender/go-matroska#1]
After install and redme example have error 
`src/github.com/pixelbender/go-matroska/ebml/decode.go:172: dec.buf.Discard undefined (type *bufio.Reader has no field or method Truncate)
src/github.com/pixelbender/go-matroska/ebml/decode.go:197: dec.buf.Discard undefined (type *bufio.Reader has no field or method Truncate)
src/github.com/pixelbender/go-matroska/ebml/decode.go:225: dec.buf.Discard undefined (type *bufio.Reader has no field or method Discard)
src/github.com/pixelbender/go-matroska/ebml/decode.go:313: dec.buf.Discard undefined (type *bufio.Reader has no field or method Truncate)
`

`go version go1.3.3 linux/arm`

**Comment by pixelbender** [comment]
@izac1 It's compatible only with Go 1.6+
